[package]
name = "pxp-lexer"
version = "0.1.0"
edition = "2021"
license-file.workspace = true

[dependencies]
pxp-token = { path = "../pxp-token" }
pxp-span = { path = "../pxp-span" }
pxp-bytestring = { path = "../pxp-bytestring" }
