[package]
name = "pxp-type"
version = "0.1.0"
edition = "2021"
license-file.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pxp-symbol = { path = "../pxp-symbol" }
pxp-span = { path = "../pxp-span" }